//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public string client_name { get; set; }
        public string client_phone { get; set; }
        public string client_address { get; set; }
        public Nullable<int> client_del_flag { get; set; }
        public Nullable<System.DateTime> client_del_date { get; set; }
        public Nullable<int> client_type_flag { get; set; }
        public string client_add_user { get; set; }
        public Nullable<System.DateTime> client_add_date { get; set; }
        public Nullable<System.DateTime> client_edit_date { get; set; }
        public string client_edit_user { get; set; }
        public string client_number { get; set; }
        public int client_id { get; set; }
    }
}
